### ISSUE TITLE
LED doesn't blink 

### ISSUE THREAD

**Issue by a5a5aa555oo** [lwfinger/rtl8xxxu#2]
Hi, 

Today I just noticed that this wifi dongle has a led actually and it blinks on Windows, but not on Linux. 
It would be great if this issue  is fixed, thanks a lot!

Wifi dongle: ASUS USB-N13 C1 (RTL8192FU)

**Comment by a5a5aa555oo** [comment]
To fix this issue, do i need to monitor the usb traffic on windows?
How can i get the data or log you need?

**Comment by dubhater** [comment]
The data we need is in confidential Realtek documents. :)

You can write every possible value to REG_LEDCFG1 and see if it starts to blink:
```diff
diff --git a/rtl8xxxu_core.c b/rtl8xxxu_core.c
index d5094c1..e30177f 100644
--- a/rtl8xxxu_core.c
+++ b/rtl8xxxu_core.c
@@ -7178,6 +7178,9 @@ static void rtl8xxxu_watchdog_callback(struct work_struct *work)
 			rtl8xxxu_track_cfo(priv);
 
 		rtl8xxxu_refresh_rate_mask(priv, signal, sta, false);
+
+		pr_warn("trying REG_LEDCFG1=0x%x\n", priv->package_type); // package_type is only used by RTL8710BU
+		rtl8xxxu_write8(priv, REG_LEDCFG1, priv->package_type++);
 	}
 
 out:
```

You'll need to run ``ping -i 0.5 <router>`` to generate some constant traffic.

**Comment by a5a5aa555oo** [comment]
Tested from 0x0 to 0xff for several times, none of them works.
What about testing REG_LEDCFG0, REG_LEDCFG2 or REG_LEDCFG3?

my 8192fu chip is RTL8192FU rev B (UMC) romver 0.

**Comment by dubhater** [comment]
Sure, it probably won't hurt.

**Comment by a5a5aa555oo** [comment]
REG_LEDCFG3 -> not blink
REG_LEDCFG2 -> not blink
REG_LEDCFG1 -> not blink
REG_LEDCFG0 -> blink about from 0x to 0x7f
                               not blink about from 0x80  to 0xff

Hope these info helpful.

**Comment by lwfinger** [comment]
First of all, not everyone wants the LED to blink. Some find it too distacting, and others want to minimize the power used. Frankly, I do not find the blinking useful. Why do you want it?

If  you really want blinking, you need to add code to your driver that writes an appropriate value to REG_LEDCFG0 so that yours will blink. For the reasons stated, I will not be adding that code here.

This repo only follows the code in the wireless-next repo, which has the code for the next kernel, i.e. v6.6 at the moment. If you want blinking as a permanent part of the driver, you would need to submit a patch to linux-wireless@vger.kernel.org, or convince someone else to do so. If that patch survived the review process and was added to the driver, then it would end up here.

**Comment by a5a5aa555oo** [comment]
Hi Larry,

i know this repo only accepts the patches from wireless-next, i open the issue here because the author dubhater is watching here.
i will keep finding the correct value which can enable hw-control led, and i will feedback if i find it.
Thanks for all the suggestions!

**Comment by a5a5aa555oo** [comment]
The vendor driver from [ASUS](https://dlcdnets.asus.com/pub/ASUS/wireless/USB-N13_C1/UT_USB_N13_C1_1006.zip) or [BrightX's repo](https://github.com/BrightX/rtl8192fu) makes my dongle blink.

when i use the driver from BrightX's repo, i see this in dmesg
`[  423.121748] RTW: ==> ips_leave.....LED(0x00bc0000)...`

when i use the driver from ASUS, i see this in dmesg
`[   24.862827] RTW: ==> ips_leave.....LED(0x00bc0300)...`

but both value doesn't work in rtl8xxxu. is there anything wrong in my code?

```diff --git a/rtl8xxxu_core.c b/rtl8xxxu_core.c
index ed93268..c28f2be 100644
--- a/rtl8xxxu_core.c
+++ b/rtl8xxxu_core.c
@@ -7258,6 +7258,7 @@ static void rtl8xxxu_watchdog_callback(struct work_struct *work)
 {
 	struct ieee80211_vif *vif;
 	struct rtl8xxxu_priv *priv;
+	u8 c3, c2, c1, c0;
 
 	priv = container_of(work, struct rtl8xxxu_priv, ra_watchdog.work);
 	vif = priv->vif;
@@ -7286,6 +7287,14 @@ static void rtl8xxxu_watchdog_callback(struct work_struct *work)
 			rtl8xxxu_track_cfo(priv);
 
 		rtl8xxxu_refresh_rate_mask(priv, signal, sta, false);
+
+		rtl8xxxu_write32(priv, REG_LEDCFG0, 0x00bc0000);
+		c3 = rtl8xxxu_read8(priv, REG_LEDCFG3);
+		c2 = rtl8xxxu_read8(priv, REG_LEDCFG2);
+		c1 = rtl8xxxu_read8(priv, REG_LEDCFG1);
+		c0 = rtl8xxxu_read8(priv, REG_LEDCFG0);
+		pr_warn("%x %x %x %x\n", c3, c2, c1, c0);
+
 	}
 
 out:
```

output of dmesg
`[ 1721.696676] 0 bc 3 0`

**Comment by a5a5aa555oo** [comment]
Hi @dubhater ,

im still working on it but no progress.
can you tell me what value your REG_LEDCFG0 is? mine is 0x00c20300. thanks.

**Comment by dubhater** [comment]
Sorry, I don't have the energy to get that value right now.

My advice is to give up on the hardware-controlled blinking. My RTL8192CU device also doesn't seem to have it. That's at least two devices where it doesn't work.

Just make mac80211 handle the blinking. Most of the necessary code is already there. The driver just needs to set up a trigger. You can use this for inspiration: https://github.com/torvalds/linux/commit/0cf55c21ec401632043db2b8acb7cd3bef64c9e6 This way has 100% guaranteed success rate, because the code for turning the LED on and off is available. If not in the Linux driver, then in the Windows driver.

**Comment by a5a5aa555oo** [comment]
that's ok, dont say sorry!
i just found some values that makes dongle blink correctly, such as
0x00e20303
0x00e20305
0x00e20307

i think there are more values that can make the led blink, but only realtek engineers know which is the 100% correct one .
i will stop finding it, and thanks for your help and efforts all the time! :)

**Comment by a5a5aa555oo** [comment]
![DgMtO4q](https://github.com/lwfinger/rtl8xxxu/assets/48462152/515ca563-a05a-46b1-a8a1-16e9e0eb66d1)

now i set REG_LEDCFG0 to 0x00e20303, it works great.
Thanks for all the help!
